/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.PacienteDAO;
import examples.model.Paciente;
import examples.model.Usuario;
import java.sql.Date;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Lopes
 */

/*import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;*/
    

public class telaPaciente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaPaciente.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public telaPaciente() {
                // Carrega o ícone da pasta do projeto
        ImageIcon icon = new ImageIcon(getClass().getResource("/imgs/logo.png"));

        // Define o ícone da janela
        setIconImage(icon.getImage());
    initComponents();
    setLocationRelativeTo(null); // Centraliza o JFrame na tela
    try {
        // Máscara para CPF: 000.000.000-00
        javax.swing.text.MaskFormatter formatoCPF = new javax.swing.text.MaskFormatter("###.###.###-##");
        formatoCPF.setPlaceholderCharacter('_');
        formatoCPF.install(cpfPacienteCadastro);

        // Máscara para RG: 00.000.000-0
        javax.swing.text.MaskFormatter formatoRG = new javax.swing.text.MaskFormatter("##.###.###-#");
        formatoRG.setPlaceholderCharacter('_');
        formatoRG.install(rgPacienteCadastro);

        // Máscara para Data de Nascimento: 00/00/0000
        javax.swing.text.MaskFormatter formatoData = new javax.swing.text.MaskFormatter("##/##/####");
        formatoData.setPlaceholderCharacter('_');
        formatoData.install(dataNascPacienteCadastro);
        
    // Máscara para CEP: 00000-000
    javax.swing.text.MaskFormatter formatoCEP = new javax.swing.text.MaskFormatter("#####-###");
    formatoCEP.setPlaceholderCharacter('_');
    formatoCEP.install(cepPacienteCadastro);

    // Máscara para Telefone: (00) 00000-0000
    javax.swing.text.MaskFormatter formatoTelefone = new javax.swing.text.MaskFormatter("(##) #####-####");
    formatoTelefone.setPlaceholderCharacter('_');
    formatoTelefone.install(telefoneCadastroPaciente);
 // Aplicar o filtro de capitalização no campo nomePacienteCadastro
    } catch (java.text.ParseException e) {
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nomePacienteCadastro = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dataNascPacienteCadastro = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botaoIncluirCadastroPaciente = new javax.swing.JButton();
        botaoLimparCadastroPaciente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rgPacienteCadastro = new javax.swing.JFormattedTextField();
        botaoSairAgendamento = new javax.swing.JButton();
        cpfPacienteCadastro = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        convenioPacienteCadastro = new javax.swing.JFormattedTextField();
        generoPacienteCadastro = new javax.swing.JComboBox<>();
        estadoCivilPacienteCadastro = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        conveniotfPacienteCadastro = new javax.swing.JComboBox<>();
        telefoneCadastroPaciente = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        enderecoPacienteCadastro = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        cepPacienteCadastro = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        emailPacienteCadastro = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Paciente - PrimeMed");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setMinimumSize(new java.awt.Dimension(660, 500));
        jPanel3.setName("telalogin"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(660, 500));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 31, 31));
        jLabel2.setText("Cadastro Paciente");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(31, 31, 31));
        jLabel9.setText("Nome Completo:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(31, 31, 31));
        jLabel10.setText("Data de nascimento:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(31, 31, 31));
        jLabel11.setText("CPF:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 31, 31));
        jLabel1.setText("Sexo / Gênero:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 31, 31));
        jLabel4.setText("Estado civil:");

        botaoIncluirCadastroPaciente.setBackground(new java.awt.Color(26, 74, 138));
        botaoIncluirCadastroPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoIncluirCadastroPaciente.setForeground(new java.awt.Color(255, 255, 255));
        botaoIncluirCadastroPaciente.setText("Incluir");
        botaoIncluirCadastroPaciente.setBorderPainted(false);
        botaoIncluirCadastroPaciente.setDefaultCapable(false);
        botaoIncluirCadastroPaciente.setFocusPainted(false);
        botaoIncluirCadastroPaciente.setFocusable(false);
        botaoIncluirCadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirCadastroPacienteActionPerformed(evt);
            }
        });

        botaoLimparCadastroPaciente.setBackground(new java.awt.Color(26, 74, 138));
        botaoLimparCadastroPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoLimparCadastroPaciente.setForeground(new java.awt.Color(255, 255, 255));
        botaoLimparCadastroPaciente.setText("Limpar");
        botaoLimparCadastroPaciente.setBorderPainted(false);
        botaoLimparCadastroPaciente.setDefaultCapable(false);
        botaoLimparCadastroPaciente.setFocusPainted(false);
        botaoLimparCadastroPaciente.setFocusable(false);
        botaoLimparCadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparCadastroPacienteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(31, 31, 31));
        jLabel5.setText("RG:");

        rgPacienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgPacienteCadastroActionPerformed(evt);
            }
        });

        botaoSairAgendamento.setBackground(new java.awt.Color(26, 74, 138));
        botaoSairAgendamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoSairAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        botaoSairAgendamento.setText("Sair");
        botaoSairAgendamento.setBorderPainted(false);
        botaoSairAgendamento.setDefaultCapable(false);
        botaoSairAgendamento.setFocusPainted(false);
        botaoSairAgendamento.setFocusable(false);
        botaoSairAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairAgendamentoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("E-mail");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Convênio:");

        generoPacienteCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Feminino", "Masculino" }));

        estadoCivilPacienteCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Solteiro(a)", "Casado(a)" }));
        estadoCivilPacienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoCivilPacienteCadastroActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Número Convênio:");

        conveniotfPacienteCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Sim", "Não" }));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Telefone:");

        enderecoPacienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoPacienteCadastroActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(31, 31, 31));
        jLabel13.setText("Endereço:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(31, 31, 31));
        jLabel14.setText("CEP:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cepPacienteCadastro)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoPacienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(telefoneCadastroPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botaoSairAgendamento)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cpfPacienteCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(dataNascPacienteCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addComponent(nomePacienteCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(generoPacienteCadastro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rgPacienteCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                .addComponent(estadoCivilPacienteCadastro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(0, 0, Short.MAX_VALUE))))))
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(conveniotfPacienteCadastro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(convenioPacienteCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(emailPacienteCadastro)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(botaoIncluirCadastroPaciente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaoLimparCadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomePacienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generoPacienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailPacienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascPacienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoCivilPacienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conveniotfPacienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgPacienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfPacienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convenioPacienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoPacienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepPacienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneCadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoIncluirCadastroPaciente)
                    .addComponent(botaoSairAgendamento)
                    .addComponent(botaoLimparCadastroPaciente))
                .addGap(0, 178, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 130, 700, 500);

        jPanel1.setBackground(new java.awt.Color(14, 63, 139));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/lgoobranco.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel3)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 130);

        pack();
    }//GEN-END:initComponents

    private void botaoLimparCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparCadastroPacienteActionPerformed
        // Limpar os campos
        nomePacienteCadastro.setText("");
        dataNascPacienteCadastro.setText("");
        cpfPacienteCadastro.setText("");
        rgPacienteCadastro.setText("");
        cepPacienteCadastro.setText("");
        enderecoPacienteCadastro.setText("");
        telefoneCadastroPaciente.setText("");
        conveniotfPacienteCadastro.setSelectedIndex(0);
        estadoCivilPacienteCadastro.setSelectedIndex(0);
        generoPacienteCadastro.setSelectedIndex(0);
        convenioPacienteCadastro.setText("");
    }//GEN-LAST:event_botaoLimparCadastroPacienteActionPerformed

    private void rgPacienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgPacienteCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgPacienteCadastroActionPerformed

    private void botaoSairAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairAgendamentoActionPerformed
        this.dispose();
        telaPrincipal tela = new telaPrincipal("Administrador");  // cria a tela principal
        tela.setVisible(true);  
    }//GEN-LAST:event_botaoSairAgendamentoActionPerformed

    private void botaoIncluirCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirCadastroPacienteActionPerformed
       // Pegando os valores dos campos
    String nome = nomePacienteCadastro.getText().trim();
    String dataNasc = dataNascPacienteCadastro.getText().trim();
    String cpf = cpfPacienteCadastro.getText().trim();
    String cep = cepPacienteCadastro.getText().trim();
    String genero = (String) generoPacienteCadastro.getSelectedItem();
    String estadoCivil = (String) estadoCivilPacienteCadastro.getSelectedItem();
    String rg = rgPacienteCadastro.getText().trim();
    String endereco = enderecoPacienteCadastro.getText().trim();
    String email = emailPacienteCadastro.getText().trim();
    String convenio = convenioPacienteCadastro.getText().trim();
    String conveniotf = (String) conveniotfPacienteCadastro.getSelectedItem();
    String telefone = telefoneCadastroPaciente.getText().trim();

  
    
    // Validação: Verificar se algum campo está vazio
    if (conveniotf == null ||
            nome.isEmpty() || dataNasc.isEmpty() || cpf.isEmpty() || cep.isEmpty() ||
            genero == null || genero.isEmpty() ||
            estadoCivil == null || estadoCivil.isEmpty() ||
            rg.isEmpty() || endereco.isEmpty() || email.isEmpty() || conveniotf.isEmpty() || telefone.isEmpty()) {

        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos!", "Campos obrigatórios", JOptionPane.WARNING_MESSAGE);
        return;
    }
        // Convertendo data de nascimento para java.sql.Date

    try {
        java.text.SimpleDateFormat formato = new java.text.SimpleDateFormat("dd/MM/yyyy");
        java.util.Date dataUtil = formato.parse(dataNasc);
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, "Data de nascimento inválida! Use o formato dd/MM/yyyy", "Erro de Data", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Criar o objeto Paciente
    Paciente paciente = new Paciente();
    paciente.setNome(nome);
    LocalDate dataNascimento = LocalDate.parse(dataNasc, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
    paciente.setNascimento(dataNascimento);
    paciente.setCpf(cpf);
    paciente.setRg(rg);
    paciente.setCep(cep);
    paciente.setEndereco(endereco);
    paciente.setEstadoCivil(estadoCivil);
    paciente.setTelefone(telefone);
    paciente.setEmail(email);
    paciente.setNumeroConvenio(convenio);
    paciente.setConvenio(conveniotf);
    paciente.setSexo(genero);

    // Inserir no banco usando o DAO
    PacienteDAO dao = new PacienteDAO();
    if (dao.existeCpf(cpf)) {
        JOptionPane.showMessageDialog(this, "CPF já cadastrado no sistema!");
        return;
    }

    if (dao.existeRg(rg)) {
        JOptionPane.showMessageDialog(this, "RG já cadastrado no sistema!");
        return;
    }
    
    boolean sucesso = dao.inserirPaciente(paciente);

    if (sucesso) {
        JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        // Exibir os dados no console
        System.out.println("---- Dados do Paciente Cadastrado ----");
        System.out.println("Nome: " + nome);
        System.out.println("Data de Nascimento: " + dataNasc);
        System.out.println("CPF: " + cpf);
        System.out.println("CEP: " + cep);
        System.out.println("Gênero: " + genero);
        System.out.println("Estado Civil: " + estadoCivil);
        System.out.println("RG: " + rg);
        System.out.println("Endereço: " + endereco);
        System.out.println("Email: " + email);
        System.out.println("Convênio: " + convenio);
        System.out.println("Convênio Ativo: " + conveniotf);
        System.out.println("Telefone: " + telefone);

    } else {
        JOptionPane.showMessageDialog(this, "Erro ao salvar o paciente no banco!", "Erro", JOptionPane.ERROR_MESSAGE);
    }

    
    }//GEN-LAST:event_botaoIncluirCadastroPacienteActionPerformed

    private void estadoCivilPacienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoCivilPacienteCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoCivilPacienteCadastroActionPerformed

    private void enderecoPacienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoPacienteCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoPacienteCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaPaciente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoIncluirCadastroPaciente;
    private javax.swing.JButton botaoLimparCadastroPaciente;
    private javax.swing.JButton botaoSairAgendamento;
    private javax.swing.JFormattedTextField cepPacienteCadastro;
    private javax.swing.JFormattedTextField convenioPacienteCadastro;
    private javax.swing.JComboBox<String> conveniotfPacienteCadastro;
    private javax.swing.JFormattedTextField cpfPacienteCadastro;
    private javax.swing.JFormattedTextField dataNascPacienteCadastro;
    private javax.swing.JFormattedTextField emailPacienteCadastro;
    private javax.swing.JFormattedTextField enderecoPacienteCadastro;
    private javax.swing.JComboBox<String> estadoCivilPacienteCadastro;
    private javax.swing.JComboBox<String> generoPacienteCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFormattedTextField nomePacienteCadastro;
    private javax.swing.JFormattedTextField rgPacienteCadastro;
    private javax.swing.JFormattedTextField telefoneCadastroPaciente;
    // End of variables declaration//GEN-END:variables
}
