/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.ImageIcon;

/**
 *
 * @author Lopes
 */

public class telaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaPrincipal.class.getName());

    
    public telaPrincipal(String administrador) {
        initComponents();
                // Carrega o ícone da pasta do projeto
        ImageIcon icon = new ImageIcon(getClass().getResource("/imgs/logo.png"));

        // Define o ícone da janela
        setIconImage(icon.getImage());
        setLocationRelativeTo(null); // Centraliza o JFrame na tela
    }
    // Após autenticar com sucesso e pegar o nome do usuário

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel3 = new javax.swing.JPanel();
        SejaBemVindo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        botaoSairMenuPrincipal = new javax.swing.JButton();
        botaoConsulta = new javax.swing.JButton();
        botaoProntuario = new javax.swing.JButton();
        cadastroPaciente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Home - PrimeMed");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(700, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setMinimumSize(new java.awt.Dimension(660, 500));
        jPanel3.setName("telalogin"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(660, 500));

        SejaBemVindo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SejaBemVindo.setText("Seja bem vindo(a) PrimeMed");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("- Agendamento");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("- Cadastro Equipe");
        jButton3.setAlignmentY(0.0F);
        jButton3.setAutoscrolls(true);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setDefaultCapable(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("- Exame ");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setDefaultCapable(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        botaoSairMenuPrincipal.setBackground(new java.awt.Color(2, 51, 113));
        botaoSairMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoSairMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        botaoSairMenuPrincipal.setActionCommand("Sair");
        botaoSairMenuPrincipal.setAlignmentY(0.0F);
        botaoSairMenuPrincipal.setBorderPainted(false);
        botaoSairMenuPrincipal.setDefaultCapable(false);
        botaoSairMenuPrincipal.setFocusPainted(false);
        botaoSairMenuPrincipal.setFocusable(false);
        botaoSairMenuPrincipal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoSairMenuPrincipal.setLabel("Sair");
        botaoSairMenuPrincipal.setRequestFocusEnabled(false);
        botaoSairMenuPrincipal.setRolloverEnabled(false);
        botaoSairMenuPrincipal.setVerifyInputWhenFocusTarget(false);
        botaoSairMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairMenuPrincipalActionPerformed(evt);
            }
        });

        botaoConsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoConsulta.setText("- Consulta");
        botaoConsulta.setBorderPainted(false);
        botaoConsulta.setContentAreaFilled(false);
        botaoConsulta.setDefaultCapable(false);
        botaoConsulta.setFocusPainted(false);
        botaoConsulta.setFocusable(false);
        botaoConsulta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultaActionPerformed(evt);
            }
        });

        botaoProntuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoProntuario.setText("- Prontuario");
        botaoProntuario.setBorderPainted(false);
        botaoProntuario.setContentAreaFilled(false);
        botaoProntuario.setDefaultCapable(false);
        botaoProntuario.setFocusPainted(false);
        botaoProntuario.setFocusable(false);
        botaoProntuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProntuarioActionPerformed(evt);
            }
        });

        cadastroPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastroPaciente.setText("- Cadastro Paciente");
        cadastroPaciente.setAlignmentY(0.0F);
        cadastroPaciente.setAutoscrolls(true);
        cadastroPaciente.setBorderPainted(false);
        cadastroPaciente.setContentAreaFilled(false);
        cadastroPaciente.setDefaultCapable(false);
        cadastroPaciente.setFocusPainted(false);
        cadastroPaciente.setFocusable(false);
        cadastroPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoConsulta)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoProntuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(botaoSairMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(SejaBemVindo)))
                .addGap(72, 72, 72))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(SejaBemVindo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoProntuario)
                .addGap(7, 7, 7)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastroPaciente)
                    .addComponent(botaoSairMenuPrincipal))
                .addContainerGap(263, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 130, 700, 500);

        jPanel1.setBackground(new java.awt.Color(14, 63, 139));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/lgoobranco.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addContainerGap(461, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 130);

        pack();
    }//GEN-END:initComponents

    private void botaoProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProntuarioActionPerformed
        this.dispose();
        telaProntuario tela = new telaProntuario();  // Cria a Tela de Consulta
        tela.setVisible(true);
    }//GEN-LAST:event_botaoProntuarioActionPerformed

    private void botaoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultaActionPerformed
        this.dispose();
        telaConsulta tela = new telaConsulta();  // Cria a Tela de Consulta
        tela.setVisible(true);
    }//GEN-LAST:event_botaoConsultaActionPerformed

    private void botaoSairMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairMenuPrincipalActionPerformed
        this.dispose();
        telaLogin tela = new telaLogin();  // Sai da Tela Principal
        tela.setVisible(true);
    }//GEN-LAST:event_botaoSairMenuPrincipalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        telaExame tela = new telaExame();  // Cria a Tela de Agendamento
        tela.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        telaColaborador tela = new telaColaborador();  // Cria a Tela de Cadastro
        tela.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        telaAgendamento tela = new telaAgendamento();  // Cria a Tela de Agendamento
        tela.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPacienteActionPerformed
                                      
        this.dispose();
        telaPaciente tela = new telaPaciente();  // Cria a Tela de Cadastro
        tela.setVisible(true);                 // TODO add your handling code here:
    }//GEN-LAST:event_cadastroPacienteActionPerformed

    public void atualizarContadorAgendamentos(int novoValor) { // ATUALIZAR VALOR AGENDA
    
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaPrincipal("Administrador").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SejaBemVindo;
    private javax.swing.JButton botaoConsulta;
    private javax.swing.JButton botaoProntuario;
    private javax.swing.JButton botaoSairMenuPrincipal;
    private javax.swing.JButton cadastroPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
