/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Lopes
 */

import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;


    

public class telaConsulta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaConsulta.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public telaConsulta() {
                // Carrega o ícone da pasta do projeto
        ImageIcon icon = new ImageIcon(getClass().getResource("/imgs/logo.png"));

        // Define o ícone da janela
        setIconImage(icon.getImage());
initComponents();
setLocationRelativeTo(null); // Centraliza o JFrame na tela
    try {
        
        // Máscara para Horário do Exame: 00:00
        javax.swing.text.MaskFormatter formatoHora = new javax.swing.text.MaskFormatter("##:##");
        formatoHora.setPlaceholderCharacter('_');
        formatoHora.install(horarioConsulta);
 // Aplicar o filtro de capitalização no campo nomePacienteCadastro
    } catch (java.text.ParseException e) {
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nomePacienteConsulta = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botaoIncluirExame = new javax.swing.JButton();
        botaoLimparExame = new javax.swing.JButton();
        botaoSairAgendamento = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        horarioConsulta = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        diagnosticoConsulta = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        obsConsulta = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        medicamentosConsulta = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        alergiasConsulta = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta - PrimeMed");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setMinimumSize(new java.awt.Dimension(660, 500));
        jPanel3.setName("telalogin"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(660, 500));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 31, 31));
        jLabel2.setText("Consulta");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(31, 31, 31));
        jLabel9.setText("Nome Paciente:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(31, 31, 31));
        jLabel10.setText("Diagnóstico:");

        botaoIncluirExame.setBackground(new java.awt.Color(26, 74, 138));
        botaoIncluirExame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoIncluirExame.setForeground(new java.awt.Color(255, 255, 255));
        botaoIncluirExame.setText("Incluir");
        botaoIncluirExame.setBorderPainted(false);
        botaoIncluirExame.setDefaultCapable(false);
        botaoIncluirExame.setFocusPainted(false);
        botaoIncluirExame.setFocusable(false);
        botaoIncluirExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirExameActionPerformed(evt);
            }
        });

        botaoLimparExame.setBackground(new java.awt.Color(26, 74, 138));
        botaoLimparExame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoLimparExame.setForeground(new java.awt.Color(255, 255, 255));
        botaoLimparExame.setText("Limpar");
        botaoLimparExame.setBorderPainted(false);
        botaoLimparExame.setDefaultCapable(false);
        botaoLimparExame.setFocusPainted(false);
        botaoLimparExame.setFocusable(false);
        botaoLimparExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparExameActionPerformed(evt);
            }
        });

        botaoSairAgendamento.setBackground(new java.awt.Color(26, 74, 138));
        botaoSairAgendamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoSairAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        botaoSairAgendamento.setText("Sair");
        botaoSairAgendamento.setBorderPainted(false);
        botaoSairAgendamento.setDefaultCapable(false);
        botaoSairAgendamento.setFocusPainted(false);
        botaoSairAgendamento.setFocusable(false);
        botaoSairAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairAgendamentoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Orientações:");

        horarioConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioConsultaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Horário:");

        diagnosticoConsulta.setColumns(20);
        diagnosticoConsulta.setRows(5);
        jScrollPane1.setViewportView(diagnosticoConsulta);

        obsConsulta.setColumns(20);
        obsConsulta.setRows(5);
        jScrollPane2.setViewportView(obsConsulta);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Medicamentos em Uso:");

        medicamentosConsulta.setColumns(20);
        medicamentosConsulta.setRows(5);
        jScrollPane3.setViewportView(medicamentosConsulta);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Alergias:");

        alergiasConsulta.setColumns(20);
        alergiasConsulta.setRows(5);
        jScrollPane4.setViewportView(alergiasConsulta);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(botaoIncluirExame)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaoLimparExame, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoSairAgendamento))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                .addComponent(nomePacienteConsulta))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane4)
                                .addComponent(horarioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomePacienteConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horarioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoIncluirExame)
                    .addComponent(botaoSairAgendamento)
                    .addComponent(botaoLimparExame))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 130, 700, 500);

        jPanel1.setBackground(new java.awt.Color(14, 63, 139));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/lgoobranco.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel3)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 130);

        pack();
    }//GEN-END:initComponents

    private void botaoLimparExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparExameActionPerformed
        nomePacienteConsulta.setText(""); // Limpar do Cadastro
        obsConsulta.setText("");
        diagnosticoConsulta.setText("");
        horarioConsulta.setText("");
        alergiasConsulta.setText("");
        medicamentosConsulta.setText("");
    }//GEN-LAST:event_botaoLimparExameActionPerformed

    private void botaoSairAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairAgendamentoActionPerformed
        this.dispose();
        telaPrincipal tela = new telaPrincipal("Administrador");  // cria a tela principal
        tela.setVisible(true);  
    }//GEN-LAST:event_botaoSairAgendamentoActionPerformed

    private void botaoIncluirExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirExameActionPerformed
   String nomePaciente = nomePacienteConsulta.getText().trim();
        String horario = horarioConsulta.getText().trim();
        String diagnostico = diagnosticoConsulta.getText().trim();
        String obs = obsConsulta.getText().trim();
        String alergias = alergiasConsulta.getText().trim();
        String medicamentos = medicamentosConsulta.getText().trim();

        // Validação do nome
        if (nomePaciente.isEmpty() || nomePaciente.length() > 32) {
            JOptionPane.showMessageDialog(this, "Nome do paciente inválido (máx 32 caracteres).");
            return;
        }


        // Validação do horário (formato HH:MM e dentro do horário de atendimento)
        if (!horario.matches("\\d{2}:\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Horário inválido. Formato esperado: HH:MM (ex: 08:30).");
            return;
        }

        try {
            String[] partes = horario.split(":");
            int hora = Integer.parseInt(partes[0]);
            int minuto = Integer.parseInt(partes[1]);

            if (hora < 7 || hora > 22 || minuto < 0 || minuto > 59) {
                JOptionPane.showMessageDialog(this, "Horário fora do período permitido (07:00 às 22:00).");
                return;
            }

            if (hora == 22 && minuto > 0) {
                JOptionPane.showMessageDialog(this, "O último horário permitido é 22:00.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro ao validar o horário. Verifique o formato (ex: 08:30).");
            return;
        }

        // Verificação se os campos de exame e finalidade estão preenchidos
        if (diagnostico.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o diagnostico do exame.");
            return;
        }

        if (obs.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha as observações do exame.");
            return;
        }
        
        // Exibir confirmação
        JOptionPane.showMessageDialog(this, 
            "Exame incluído com sucesso!\n\n"
            + "Nome do Paciente: " + nomePaciente + "\n"
            + "Horário: " + horario + "\n"
            + "Medicamentos em uso:\n" + medicamentos + "\n\n"
            + "Alergias:\n" + alergias + "\n\n"
            + "Diagnostico:\n" + diagnostico + "\n\n"
            + "Observações:\n" + obs
        );

        // Limpar os campos após inclusão
        nomePacienteConsulta.setText("");
        horarioConsulta.setText("");
        diagnosticoConsulta.setText("");
        obsConsulta.setText("");
        alergiasConsulta.setText("");
        medicamentosConsulta.setText("");
    
    }//GEN-LAST:event_botaoIncluirExameActionPerformed

    private void horarioConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horarioConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaConsulta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alergiasConsulta;
    private javax.swing.JButton botaoIncluirExame;
    private javax.swing.JButton botaoLimparExame;
    private javax.swing.JButton botaoSairAgendamento;
    private javax.swing.JTextArea diagnosticoConsulta;
    private javax.swing.JFormattedTextField horarioConsulta;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea medicamentosConsulta;
    private javax.swing.JFormattedTextField nomePacienteConsulta;
    private javax.swing.JTextArea obsConsulta;
    // End of variables declaration//GEN-END:variables
}
