/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.UsuarioDAO;
import examples.model.Usuario;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Lopes
 */

/*import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;*/
    

public class telaColaborador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaColaborador.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public telaColaborador() {
                // Carrega o ícone da pasta do projeto
        ImageIcon icon = new ImageIcon(getClass().getResource("/imgs/logo.png"));

        // Define o ícone da janela
        setIconImage(icon.getImage());
    initComponents();
    setLocationRelativeTo(null); // Centraliza o JFrame na tela
    try {
        // Máscara para CPF: 000.000.000-00
        javax.swing.text.MaskFormatter formatoCPF = new javax.swing.text.MaskFormatter("###.###.###-##");
        formatoCPF.setPlaceholderCharacter('_');
        formatoCPF.install(cpfColaborador);

        // Máscara para RG: 00.000.000-0
        javax.swing.text.MaskFormatter formatoRG = new javax.swing.text.MaskFormatter("##.###.###-#");
        formatoRG.setPlaceholderCharacter('_');
        formatoRG.install(rgColaborador);

        // Máscara para Data de Nascimento: 00/00/0000
        javax.swing.text.MaskFormatter formatoData = new javax.swing.text.MaskFormatter("##/##/####");
        formatoData.setPlaceholderCharacter('_');
        formatoData.install(dataNascColaborador);
        
    // Máscara para CEP: 00000-000
    javax.swing.text.MaskFormatter formatoCEP = new javax.swing.text.MaskFormatter("#####-###");
    formatoCEP.setPlaceholderCharacter('_');
    formatoCEP.install(cepColaborador);

    // Máscara para Telefone: (00) 00000-0000
    javax.swing.text.MaskFormatter formatoTelefone = new javax.swing.text.MaskFormatter("(##) #####-####");
    formatoTelefone.setPlaceholderCharacter('_');
    formatoTelefone.install(telefoneColaborador);
 // Aplicar o filtro de capitalização no campo nomePacienteCadastro
    } catch (java.text.ParseException e) {
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nomeColaborador = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dataNascColaborador = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botaoIncluirCadastroColaborador = new javax.swing.JButton();
        botaoLimparCadastroColaborador = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rgColaborador = new javax.swing.JFormattedTextField();
        botaoSairAgendamento = new javax.swing.JButton();
        cpfColaborador = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        crmColaborador = new javax.swing.JFormattedTextField();
        generoColaborador = new javax.swing.JComboBox<>();
        estadoCivilColaborador = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        permColaborador = new javax.swing.JComboBox<>();
        telefoneColaborador = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        enderecoColaborador = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        cepColaborador = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        especialidadeColaborador = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Colaborador - PrimeMed");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setMinimumSize(new java.awt.Dimension(660, 500));
        jPanel3.setName("telalogin"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(660, 500));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 31, 31));
        jLabel2.setText("Cadastro Colaborador");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(31, 31, 31));
        jLabel9.setText("Nome Completo:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(31, 31, 31));
        jLabel10.setText("Data de nascimento:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(31, 31, 31));
        jLabel11.setText("CPF:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 31, 31));
        jLabel1.setText("Sexo / Gênero:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 31, 31));
        jLabel4.setText("Estado civil:");

        botaoIncluirCadastroColaborador.setBackground(new java.awt.Color(26, 74, 138));
        botaoIncluirCadastroColaborador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoIncluirCadastroColaborador.setForeground(new java.awt.Color(255, 255, 255));
        botaoIncluirCadastroColaborador.setText("Incluir");
        botaoIncluirCadastroColaborador.setBorderPainted(false);
        botaoIncluirCadastroColaborador.setDefaultCapable(false);
        botaoIncluirCadastroColaborador.setFocusPainted(false);
        botaoIncluirCadastroColaborador.setFocusable(false);
        botaoIncluirCadastroColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirCadastroColaboradorActionPerformed(evt);
            }
        });

        botaoLimparCadastroColaborador.setBackground(new java.awt.Color(26, 74, 138));
        botaoLimparCadastroColaborador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoLimparCadastroColaborador.setForeground(new java.awt.Color(255, 255, 255));
        botaoLimparCadastroColaborador.setText("Limpar");
        botaoLimparCadastroColaborador.setBorderPainted(false);
        botaoLimparCadastroColaborador.setDefaultCapable(false);
        botaoLimparCadastroColaborador.setFocusPainted(false);
        botaoLimparCadastroColaborador.setFocusable(false);
        botaoLimparCadastroColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparCadastroColaboradorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(31, 31, 31));
        jLabel5.setText("RG:");

        rgColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgColaboradorActionPerformed(evt);
            }
        });

        botaoSairAgendamento.setBackground(new java.awt.Color(26, 74, 138));
        botaoSairAgendamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoSairAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        botaoSairAgendamento.setText("Sair");
        botaoSairAgendamento.setBorderPainted(false);
        botaoSairAgendamento.setDefaultCapable(false);
        botaoSairAgendamento.setFocusPainted(false);
        botaoSairAgendamento.setFocusable(false);
        botaoSairAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairAgendamentoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Especialidade");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Permissão:");

        crmColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crmColaboradorActionPerformed(evt);
            }
        });

        generoColaborador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Feminino", "Masculino" }));

        estadoCivilColaborador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Solteiro(a)", "Casado(a)" }));
        estadoCivilColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoCivilColaboradorActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("CRM:");

        permColaborador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Profissional da Saúde" }));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Telefone:");

        enderecoColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoColaboradorActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(31, 31, 31));
        jLabel13.setText("Endereço:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(31, 31, 31));
        jLabel14.setText("CEP:");

        especialidadeColaborador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Clínica Geral", "Cardiologia", "Dermatologia", "Ginecologia", "Pediatria", "Ortopedia", "Neurologia", "Psiquiatria", "Oftalmologia", "Otorrinolaringologia", "Endocrinologia" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cepColaborador)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(telefoneColaborador, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botaoSairAgendamento)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cpfColaborador, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(dataNascColaborador, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addComponent(nomeColaborador, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(generoColaborador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rgColaborador, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                .addComponent(estadoCivilColaborador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(0, 0, Short.MAX_VALUE))))))
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(permColaborador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(crmColaborador, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(especialidadeColaborador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(botaoIncluirCadastroColaborador)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaoLimparCadastroColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(especialidadeColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoCivilColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(permColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crmColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoIncluirCadastroColaborador)
                    .addComponent(botaoSairAgendamento)
                    .addComponent(botaoLimparCadastroColaborador))
                .addGap(0, 178, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 130, 700, 500);

        jPanel1.setBackground(new java.awt.Color(14, 63, 139));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/lgoobranco.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel3)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 130);

        pack();
    }//GEN-END:initComponents

    private void botaoLimparCadastroColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparCadastroColaboradorActionPerformed
        // Limpar os campos
        nomeColaborador.setText("");
        dataNascColaborador.setText("");
        cpfColaborador.setText("");
        rgColaborador.setText("");
        cepColaborador.setText("");
        enderecoColaborador.setText("");
        telefoneColaborador.setText("");
        permColaborador.setSelectedIndex(0);
        estadoCivilColaborador.setSelectedIndex(0);
        generoColaborador.setSelectedIndex(0);
        crmColaborador.setText("");
    }//GEN-LAST:event_botaoLimparCadastroColaboradorActionPerformed

    private void rgColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgColaboradorActionPerformed

    private void botaoSairAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairAgendamentoActionPerformed
        this.dispose();
        telaPrincipal tela = new telaPrincipal("Administrador");  // cria a tela principal
        tela.setVisible(true);  
    }//GEN-LAST:event_botaoSairAgendamentoActionPerformed

    private void botaoIncluirCadastroColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirCadastroColaboradorActionPerformed
                                                               
    try {
        // Coletar os dados da tela
        String nome = nomeColaborador.getText().trim();
        String cpf = cpfColaborador.getText().trim();
        String nascimentoStr = dataNascColaborador.getText().trim();
        String sexo = generoColaborador.getSelectedItem().toString();
        String estadoCivil = estadoCivilColaborador.getSelectedItem().toString();
        String rg = rgColaborador.getText().trim();
        String cep = cepColaborador.getText().trim();
        String endereco = enderecoColaborador.getText().trim();
        String telefone = telefoneColaborador.getText().trim();
        String crm = crmColaborador.getText().trim();
        String tipoUsuario = permColaborador.getSelectedItem().toString();
        String especialidade = "EspecialidadeTeste"; // Troque por seu campo real de especialidade, se tiver

        // =============================
        // Validação de todos os campos obrigatórios
        // =============================
        if (nome.isEmpty() || cpf.isEmpty() || nascimentoStr.isEmpty() || 
            sexo.equalsIgnoreCase("Selecione") || estadoCivil.equalsIgnoreCase("Selecione") || 
            rg.isEmpty() || cep.isEmpty() || endereco.isEmpty() || telefone.isEmpty() || 
            tipoUsuario.equalsIgnoreCase("Selecione") || especialidade.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Por favor, preencha TODOS os campos antes de salvar!");
            return;
        }
        

        UsuarioDAO usuarioDAO = new UsuarioDAO();

        // Verifica se o CRM já existe
        if (usuarioDAO.crmExiste(crm)) {
            JOptionPane.showMessageDialog(this, "CRM já cadastrado! Informe um CRM diferente.");
            return;
        }

        // Verifica se o CPF já existe
        if (usuarioDAO.cpfExiste(cpf)) {
            JOptionPane.showMessageDialog(this, "CPF já cadastrado! Informe um CPF diferente.");
            return;
        }
        

        // Validar formato da data
        LocalDate nascimento;
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            nascimento = LocalDate.parse(nascimentoStr, formatter);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data de nascimento inválida! Use o formato dd/MM/yyyy.");
            return;
        }

        // Criar o objeto Usuario
        Usuario usuario = new Usuario(
            nome,
            cpf,
            nascimento,
            sexo,
            estadoCivil,
            rg,
            cep,
            endereco,
            telefone,
            crm,
            tipoUsuario,
            especialidade
        );

        // Salvar no banco
        
        usuarioDAO.cadastrarUsuario(usuario);

        // Limpar os campos após salvar com sucesso
        nomeColaborador.setText("");
        dataNascColaborador.setText("");
        cpfColaborador.setText("");
        rgColaborador.setText("");
        cepColaborador.setText("");
        enderecoColaborador.setText("");
        telefoneColaborador.setText("");
        crmColaborador.setText("");
        permColaborador.setSelectedIndex(0);
        estadoCivilColaborador.setSelectedIndex(0);
        generoColaborador.setSelectedIndex(0);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao incluir cadastro: " + e.getMessage());
        e.printStackTrace();
    }

   
    
    }//GEN-LAST:event_botaoIncluirCadastroColaboradorActionPerformed

    private void estadoCivilColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoCivilColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoCivilColaboradorActionPerformed

    private void enderecoColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoColaboradorActionPerformed

    private void crmColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crmColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crmColaboradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaColaborador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoIncluirCadastroColaborador;
    private javax.swing.JButton botaoLimparCadastroColaborador;
    private javax.swing.JButton botaoSairAgendamento;
    private javax.swing.JFormattedTextField cepColaborador;
    private javax.swing.JFormattedTextField cpfColaborador;
    private javax.swing.JFormattedTextField crmColaborador;
    private javax.swing.JFormattedTextField dataNascColaborador;
    private javax.swing.JFormattedTextField enderecoColaborador;
    private javax.swing.JComboBox<String> especialidadeColaborador;
    private javax.swing.JComboBox<String> estadoCivilColaborador;
    private javax.swing.JComboBox<String> generoColaborador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFormattedTextField nomeColaborador;
    private javax.swing.JComboBox<String> permColaborador;
    private javax.swing.JFormattedTextField rgColaborador;
    private javax.swing.JFormattedTextField telefoneColaborador;
    // End of variables declaration//GEN-END:variables
}
