/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Lopes
 */

import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;


    

public class telaProntuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaProntuario.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public telaProntuario() {
initComponents();
        // Carrega o ícone da pasta do projeto
        ImageIcon icon = new ImageIcon(getClass().getResource("/imgs/logo.png"));

        // Define o ícone da janela
        setIconImage(icon.getImage());
setLocationRelativeTo(null); // Centraliza o JFrame na tela
    try {
        
        // Máscara para Horário do Exame: 00:00
        javax.swing.text.MaskFormatter formatoHora = new javax.swing.text.MaskFormatter("##:##");
        formatoHora.setPlaceholderCharacter('_');
        formatoHora.install(horarioProntuario);
 // Aplicar o filtro de capitalização no campo nomePacienteCadastro
    } catch (java.text.ParseException e) {
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nomePacienteProntuario = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botaoIncluirProntuario = new javax.swing.JButton();
        botaoLimparProntuario = new javax.swing.JButton();
        botaoSairAgendamento = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        horarioProntuario = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        queixasProntuario = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        alergiasProntuario = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        medicamentosProntuario = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        historicoProntuario = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta - PrimeMed");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setMinimumSize(new java.awt.Dimension(660, 500));
        jPanel3.setName("telalogin"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(660, 500));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 31, 31));
        jLabel2.setText("Prontuario");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(31, 31, 31));
        jLabel9.setText("Nome Paciente:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(31, 31, 31));
        jLabel10.setText("Queixas Principais:");

        botaoIncluirProntuario.setBackground(new java.awt.Color(26, 74, 138));
        botaoIncluirProntuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoIncluirProntuario.setForeground(new java.awt.Color(255, 255, 255));
        botaoIncluirProntuario.setText("Incluir");
        botaoIncluirProntuario.setBorderPainted(false);
        botaoIncluirProntuario.setDefaultCapable(false);
        botaoIncluirProntuario.setFocusPainted(false);
        botaoIncluirProntuario.setFocusable(false);
        botaoIncluirProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirProntuarioActionPerformed(evt);
            }
        });

        botaoLimparProntuario.setBackground(new java.awt.Color(26, 74, 138));
        botaoLimparProntuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoLimparProntuario.setForeground(new java.awt.Color(255, 255, 255));
        botaoLimparProntuario.setText("Limpar");
        botaoLimparProntuario.setBorderPainted(false);
        botaoLimparProntuario.setDefaultCapable(false);
        botaoLimparProntuario.setFocusPainted(false);
        botaoLimparProntuario.setFocusable(false);
        botaoLimparProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparProntuarioActionPerformed(evt);
            }
        });

        botaoSairAgendamento.setBackground(new java.awt.Color(26, 74, 138));
        botaoSairAgendamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoSairAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        botaoSairAgendamento.setText("Sair");
        botaoSairAgendamento.setBorderPainted(false);
        botaoSairAgendamento.setDefaultCapable(false);
        botaoSairAgendamento.setFocusPainted(false);
        botaoSairAgendamento.setFocusable(false);
        botaoSairAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairAgendamentoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Alergias:");

        horarioProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioProntuarioActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Horário:");

        queixasProntuario.setColumns(20);
        queixasProntuario.setRows(5);
        jScrollPane1.setViewportView(queixasProntuario);

        alergiasProntuario.setColumns(20);
        alergiasProntuario.setRows(5);
        jScrollPane2.setViewportView(alergiasProntuario);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Medicamentos em Uso:");

        medicamentosProntuario.setColumns(20);
        medicamentosProntuario.setRows(5);
        jScrollPane3.setViewportView(medicamentosProntuario);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Histórico Familiar:");

        historicoProntuario.setColumns(20);
        historicoProntuario.setRows(5);
        jScrollPane4.setViewportView(historicoProntuario);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(botaoIncluirProntuario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaoLimparProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoSairAgendamento))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                .addComponent(nomePacienteProntuario))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane4)
                                .addComponent(horarioProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomePacienteProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horarioProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoIncluirProntuario)
                    .addComponent(botaoSairAgendamento)
                    .addComponent(botaoLimparProntuario))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 130, 700, 500);

        jPanel1.setBackground(new java.awt.Color(14, 63, 139));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/lgoobranco.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel3)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 130);

        pack();
    }//GEN-END:initComponents

    private void botaoLimparProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparProntuarioActionPerformed
        nomePacienteProntuario.setText(""); // Limpar do Cadastro
        alergiasProntuario.setText("");
        queixasProntuario.setText("");
        horarioProntuario.setText("");
        historicoProntuario.setText("");
        medicamentosProntuario.setText("");
        alergiasProntuario.setText("");
    }//GEN-LAST:event_botaoLimparProntuarioActionPerformed

    private void botaoSairAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairAgendamentoActionPerformed
        this.dispose();
        telaPrincipal tela = new telaPrincipal("Administrador");  // cria a tela principal
        tela.setVisible(true);  
    }//GEN-LAST:event_botaoSairAgendamentoActionPerformed

    private void botaoIncluirProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirProntuarioActionPerformed
   String nomePaciente = nomePacienteProntuario.getText().trim();
    String horario = horarioProntuario.getText().trim();
    String queixas = queixasProntuario.getText().trim();
    String alergias = alergiasProntuario.getText().trim();
    String historico = historicoProntuario.getText().trim();
    String medicamentos = medicamentosProntuario.getText().trim();

    // Validação do nome
    if (nomePaciente.isEmpty() || nomePaciente.length() > 32) {
        JOptionPane.showMessageDialog(this, "Nome do paciente inválido (máx 32 caracteres).");
        return;
    }

    try {
    String[] partes = horario.split(":");
    int hora = Integer.parseInt(partes[0]);
    int minuto = Integer.parseInt(partes[1]);

    if (hora < 7 || hora > 22 || minuto < 0 || minuto > 59) {
        JOptionPane.showMessageDialog(this, "Horário fora do período permitido (07:00 às 22:00).");
        return;
    }

    if (hora == 22 && minuto > 0) {
        JOptionPane.showMessageDialog(this, "O último horário permitido é 22:00.");
        return;
    }
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Erro ao validar o horário. Verifique o formato HH:MM (ex: 08:30).");
    return;
}

    // Validação dos campos obrigatórios de texto
    if (queixas.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha as queixas.");
        return;
    }

    if (alergias.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha as alergias.");
        return;
    }

    if (historico.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha o histórico.");
        return;
    }

    if (medicamentos.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha os medicamentos.");
        return;
    }

    // Exibir confirmação
    JOptionPane.showMessageDialog(this,
        "Prontuário incluído com sucesso!\n\n"
        + "Nome do Paciente: " + nomePaciente + "\n"
        + "Horário: " + horario + "\n"
        + "Queixas:\n" + queixas + "\n\n"
        + "Histórico:\n" + historico + "\n\n"
        + "Alergias:\n" + alergias + "\n\n"
        + "Medicamentos:\n" + medicamentos
    );

    // Limpar os campos após inclusão
    nomePacienteProntuario.setText("");
    horarioProntuario.setText("");
    queixasProntuario.setText("");
    alergiasProntuario.setText("");
    historicoProntuario.setText("");
    medicamentosProntuario.setText("");

    }//GEN-LAST:event_botaoIncluirProntuarioActionPerformed

    private void horarioProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioProntuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horarioProntuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaProntuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alergiasProntuario;
    private javax.swing.JButton botaoIncluirProntuario;
    private javax.swing.JButton botaoLimparProntuario;
    private javax.swing.JButton botaoSairAgendamento;
    private javax.swing.JTextArea historicoProntuario;
    private javax.swing.JFormattedTextField horarioProntuario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea medicamentosProntuario;
    private javax.swing.JFormattedTextField nomePacienteProntuario;
    private javax.swing.JTextArea queixasProntuario;
    // End of variables declaration//GEN-END:variables
}
