/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import connect.ConnectFactory;
import dao.UsuarioDAO;
import java.text.ParseException;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Lopes
 */
public class telaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaLogin.class.getName());

    /**
     * Creates new form interfaceprincipal
     */
    public telaLogin() {
        
        initComponents();
        
                // Carrega o ícone da pasta do projeto
        ImageIcon icon = new ImageIcon(getClass().getResource("/imgs/logo.png"));

        // Define o ícone da janela
        setIconImage(icon.getImage());
        try {
            ConnectFactory a = new ConnectFactory();
            a.getConnection();
            System.out.println("Conectado com sucesso");

            } catch (Exception e) {
                System.out.println("Programa não conectado");
            }
        
        setLocationRelativeTo(null); // Centraliza o JFrame na tela
        try {
            javax.swing.text.MaskFormatter formatoCPF = new javax.swing.text.MaskFormatter("###.###.###-##");
            formatoCPF.setPlaceholderCharacter('_');
            formatoCPF.install(cpfLogin);  // Aplica a máscara ao campo existente
        } catch (java.text.ParseException e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        actionEntrarLogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cpfLogin = new javax.swing.JFormattedTextField();
        senhaLogin = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login - PrimeMed");
        setBackground(new java.awt.Color(255, 51, 51));
        setMinimumSize(new java.awt.Dimension(467, 403));
        setResizable(false);
        getContentPane().setLayout(null);

        actionEntrarLogin.setBackground(new java.awt.Color(26, 74, 138));
        actionEntrarLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        actionEntrarLogin.setForeground(new java.awt.Color(255, 255, 255));
        actionEntrarLogin.setText("Entrar");
        actionEntrarLogin.setBorderPainted(false);
        actionEntrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionEntrarLoginActionPerformed(evt);
            }
        });
        getContentPane().add(actionEntrarLogin);
        actionEntrarLogin.setBounds(150, 290, 130, 40);

        jPanel1.setBackground(new java.awt.Color(14, 63, 139));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/lgoobranco.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel3)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 130);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setName("telalogin"); // NOI18N

        cpfLogin.setText("000.000.000-00");
        cpfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfLoginActionPerformed(evt);
            }
        });

        senhaLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        senhaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaLoginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("CPF:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Senha:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 130, 500, 300);

        pack();
    }//GEN-END:initComponents

    private void senhaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaLoginActionPerformed

    
    
    private void actionEntrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionEntrarLoginActionPerformed
                                                 
    String usuario = cpfLogin.getText().trim();
    String senha = new String(senhaLogin.getPassword()).trim();

    // Validação básica do formato do CPF
    if (!usuario.matches("\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}")) {
        JOptionPane.showMessageDialog(this, "CPF inválido! Formato correto: 123.456.789-10");
        return;
    }

    UsuarioDAO dao = new UsuarioDAO();

    // Login especial do Administrador
    if (usuario.equals("000.000.000-00")) {
        if (senha.equals("00000")) {
            JOptionPane.showMessageDialog(this, "Login Administrador bem-sucedido!");
            this.dispose();
            telaPrincipal tela = new telaPrincipal("Administrador");
            tela.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Senha incorreta para o Administrador.");
        }
        return;
    }

    // Agora verifica se o CPF está cadastrado no banco
    boolean existe = dao.existeCpf(usuario);

    if (!existe) {
        JOptionPane.showMessageDialog(this, "CPF não cadastrado no sistema.");
        return;
    }

    // Se existir, valida a senha (os 5 primeiros dígitos numéricos)
    String cpfNumerico = usuario.replace(".", "").replace("-", "");
    String senhaEsperada = cpfNumerico.substring(0, 5);

    if (senha.equals(senhaEsperada)) {
        JOptionPane.showMessageDialog(this, "Login bem-sucedido!");

        // Buscar nome do usuário no banco (opcional, caso queira mostrar na tela principal)
        String nomeUsuario = dao.buscarNomePorCpf(usuario);

        this.dispose();
        telaPrincipal tela = new telaPrincipal(nomeUsuario);
        tela.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Senha incorreta! A senha deve ser os 5 primeiros dígitos do CPF.");
    }   
    }//GEN-LAST:event_actionEntrarLoginActionPerformed

    private void cpfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfLoginActionPerformed
    try {
        MaskFormatter formatoCPF = new MaskFormatter("###.###.###-##");
        formatoCPF.setPlaceholderCharacter('_');
        cpfLogin = new JFormattedTextField(formatoCPF);
    } catch (ParseException e) {
    }
    }//GEN-LAST:event_cpfLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionEntrarLogin;
    private javax.swing.JFormattedTextField cpfLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField senhaLogin;
    // End of variables declaration//GEN-END:variables
}
